name: Binding

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: iOS bindings
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add iOS targets
        run: rustup target add aarch64-apple-ios aarch64-apple-ios-sim x86_64-apple-ios

      - uses: Swatinem/rust-cache@v2

      - name: Build Swift bindings and iOS static libraries
        run: bash build_bindings.sh --arm64 --sim-arm64 --x86_64
